language: ruby
bundler_args: --without development
rvm:
  - 2.0.0-p247
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:reset --trace
  - bundle exec rspec
gemfile:
  - Gemfile
branches:
  only:
    - master
